# Generated by Django 5.2.6 on 2025-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
